<?php
$config = array (
  'debug' => 0,
  'MISP' => 
  array (
    'system_setting_db' => false,
    'python_bin' => '/usr/local/bin/python3',
    'redis_host' => 'redis',
    'redis_password' => 'redispassword',
    'redis_port' => 6379,
    'attachments_dir' => '/var/www/MISP/app/files',
    'background_jobs' => true,
    'ca_path' => '/etc/ssl/certs/ca-certificates.crt',
    'download_gpg_from_homedir' => false,
    'menu_custom_right_link' => '',
    'menu_custom_right_link_html' => '',
    'online_version_check' => true,
    'osuser' => 'www-data',
    'redis_database' => 13,
    'self_update' => false,
    'tmpdir' => '/var/www/MISP/app/tmp',
    'uuid' => '1e6a279c-bdc9-4c43-a20a-c8d3ac527a28',
    'baseurl' => 'https://192.168.1.14:7003',
    'contact' => 'admin@admin.test',
    'email' => 'admin@admin.test',
    'default_attribute_distribution' => 'event',
    'default_event_distribution' => '1',
    'default_event_tag_collection' => 0,
    'delegation' => true,
    'disable_user_login_change' => false,
    'enableEventBlocklisting' => true,
    'enableOrgBlocklisting' => true,
    'event_alert_republish_ban' => true,
    'event_alert_republish_ban_refresh_on_retry' => true,
    'event_alert_republish_ban_threshold' => 120,
    'full_tags_on_event_index' => '1',
    'incoming_tags_disabled_by_default' => false,
    'language' => 'eng',
    'log_auth' => true,
    'log_new_audit' => true,
    'proposals_block_attributes' => false,
    'server_settings_skip_backup_rotate' => false,
    'showCorrelationsOnIndex' => true,
    'showorg' => true,
    'showorgalternate' => false,
    'store_api_access_time' => false,
    'tagging' => true,
    'take_ownership_xml_import' => false,
    'terms_download' => false,
    'unpublishedprivate' => false,
    'user_email_notification_ban' => true,
    'org' => 'CyberBlue SOC',
    'external_baseurl' => 'https://192.168.1.14:7003',
    'host_org_id' => 1,
    'enable_themes' => false,
    'log_client_ip' => true,
    'log_user_ips' => true,
    'log_user_ips_authkeys' => true,
    'welcome_text_bottom' => '',
    'welcome_text_top' => '',
    'live' => true,
  ),
  'GnuPG' => 
  array (
    'binary' => '/usr/bin/gpg',
    'email' => 'admin@admin.test',
    'homedir' => '/var/www/MISP/.gnupg',
    'password' => 'passphrase',
    'onlyencrypted' => false,
  ),
  'SMIME' => 
  array (
    'enabled' => false,
  ),
  'SecureAuth' => 
  array (
    'amount' => 5,
    'expire' => 300,
  ),
  'Security' => 
  array (
    'disable_instance_file_uploads' => false,
    'disable_local_feed_access' => false,
    'rest_client_enable_arbitrary_urls' => false,
    'salt' => 'ER7%PG>OP4Sa?1*j=El4ej%Og<8gCYgr',
    'encryption_key' => '',
    'advanced_authkeys' => true,
    'alert_on_suspicious_logins' => true,
    'check_sec_fetch_site_header' => true,
    'disable_browser_cache' => true,
    'do_not_log_authkeys' => true,
    'log_each_individual_auth_fail' => true,
    'require_password_confirmation' => true,
    'username_in_response_header' => true,
    'password_policy_length' => 12,
    'password_policy_complexity' => '/^((?=.*\\d)|(?=.*\\W+))(?![\\n])(?=.*[A-Z])(?=.*[a-z]).*$|.{16,}/',
    'rest_client_baseurl' => 'https://192.168.1.14:7003',
    'csp_enforce' => true,
    'auth' => 
    array (
    ),
  ),
  'Session' => 
  array (
    'timeout' => 60,
    'cookie_timeout' => 10080,
    'defaults' => 'php',
    'autoRegenerate' => false,
    'checkAgent' => false,
    'ini' => 
    array (
      'session.cookie_secure' => true,
      'session.cookie_domain' => '',
      'session.cookie_samesite' => 'Lax',
    ),
  ),
  'Plugin' => 
  array (
    'ZeroMQ_redis_host' => 'redis',
    'ZeroMQ_redis_password' => 'redispassword',
    'ZeroMQ_redis_port' => 6379,
    'ZeroMQ_enable' => false,
    'Enrichment_hover_enable' => false,
    'Enrichment_hover_popover_only' => false,
    'Action_services_url' => 'http://misp-modules',
    'Enrichment_services_url' => 'http://misp-modules',
    'Export_services_url' => 'http://misp-modules',
    'Import_services_url' => 'http://misp-modules',
    'Action_services_enable' => true,
    'Cortex_services_enable' => false,
    'Enrichment_hover_timeout' => 5,
    'Enrichment_services_enable' => true,
    'Enrichment_timeout' => 30,
    'Export_services_enable' => true,
    'Import_services_enable' => true,
    'Workflow_enable' => true,
    'CustomAuth_enable' => false,
    'CustomAuth_header' => NULL,
    'CustomAuth_use_header_namespace' => true,
    'CustomAuth_required' => false,
    'CustomAuth_header_namespace' => 'HTTP_',
    'CustomAuth_only_allow_source' => NULL,
    'CustomAuth_name' => 'External Authentication',
    'CustomAuth_disable_logout' => false,
    'CustomAuth_custom_password_reset' => NULL,
    'CustomAuth_custom_logout' => NULL,
  ),
  'OidcAuth' => 
  array (
    'provider_url' => '',
    'issuer' => '',
    'client_id' => '',
    'client_secret' => '',
    'code_challenge_method' => '',
    'roles_property' => '',
    'role_mapper' => '',
    'default_org' => '',
  ),
  'SimpleBackgroundJobs' => 
  array (
    'redis_host' => 'redis',
    'redis_password' => 'redispassword',
    'redis_port' => 6379,
    'supervisor_host' => '127.0.0.1',
    'supervisor_password' => 'supervisor',
    'supervisor_user' => 'supervisor',
    'enabled' => true,
    'max_job_history_ttl' => 86400,
    'redis_database' => 1,
    'redis_namespace' => 'background_jobs',
    'supervisor_port' => 9001,
  ),
);